#!/usr/bin/env php
<?php

/**
 * Namespacify Command Line Tool
 *
 * Adds namespaces to all PHP classes of a given directory.
 *
 * PHP Version 5.3.10
 *
 * @category  console
 * @package   namespacify
 * @author    Florian Eckerstorfer <florian@theroadtojoy.at>
 * @license   http://opensource.org/licenses/MIT The MIT License
 * @copyright 2012 2bePUBLISHED Internet Services Austria GmbH
 */

require_once __DIR__.'/namespacify.php';
