parameters:
    finder.class:    Symfony\Component\Finder\Finder
    index.class:     Pub\Namespacify\Index\Index
    indexer.class:   Pub\Namespacify\Indexer\Indexer
    parser.class:    Pub\Namespacify\Parser\SimpleParser

services:
    finder:
        class:      %finder.class%
    index:
        class:      %index.class%
    indexer:
        class:      %indexer.class%
        calls:
            - [ setIndex, [ @index ] ]
            - [ setFinder, [ @finder ] ]
    parser:
        class:      %parser.class%
